import type { Activity } from "../../types/reindeer";
import { validateActivities } from "../../utils/validateActivities";
import exampleJson from "./exampleData.json";

const exampleValidation = validateActivities(exampleJson.activities);
if (!exampleValidation.valid) {
  console.error(
    "exampleData.json validation failed:",
    exampleValidation.errors,
  );
}
const exampleActivities: Activity[] = exampleValidation.data;

export const edgeCaseEmpty: Activity[] = [];

// Hand-crafted multi-year portfolio: 8 opportunities, ~50 activities across 2023-2025
export const multiYearPortfolio: Activity[] = [
  // --- Opp 1: Cloud Migration (2023-09-30, Launched, 350k) — 6 activities ---
  {
    id: "myp-cm-1",
    timestamp: "2023-03-10T09:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-1", name: "Cloud Migration", closeDate: "2023-09-30", stage: "Prospect", revenue: 350000, stageAdjustedRevenue: 35000 }],
  },
  {
    id: "myp-cm-2",
    timestamp: "2023-04-18T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Technical deep dive",
    linkedOpportunities: [{ id: "myp-opp-1", name: "Cloud Migration", closeDate: "2023-09-30", stage: "Qualified", revenue: 350000, stageAdjustedRevenue: 70000 }],
  },
  {
    id: "myp-cm-3",
    timestamp: "2023-05-22T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Architecture review",
    linkedOpportunities: [{ id: "myp-opp-1", name: "Cloud Migration", closeDate: "2023-09-30", stage: "Technical Validation", revenue: 350000, stageAdjustedRevenue: 140000 }],
  },
  {
    id: "myp-cm-4",
    timestamp: "2023-06-15T11:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Executive briefing",
    linkedOpportunities: [{ id: "myp-opp-1", name: "Cloud Migration", closeDate: "2023-09-30", stage: "Business Validation", revenue: 350000, stageAdjustedRevenue: 210000 }],
  },
  {
    id: "myp-cm-5",
    timestamp: "2023-07-20T15:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Contract negotiation",
    linkedOpportunities: [{ id: "myp-opp-1", name: "Cloud Migration", closeDate: "2023-09-30", stage: "Committed", revenue: 350000, stageAdjustedRevenue: 280000 }],
  },
  {
    id: "myp-cm-6",
    timestamp: "2023-09-05T09:00:00Z",
    type: "workshop",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }, { name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Go-live planning",
    linkedOpportunities: [{ id: "myp-opp-1", name: "Cloud Migration", closeDate: "2023-09-30", stage: "Launched", revenue: 350000, stageAdjustedRevenue: 350000 }],
  },
  // --- Opp 2: Mainframe Modernization (2024-03-31, Closed Lost, 500k) — 7 activities ---
  {
    id: "myp-mm-1",
    timestamp: "2023-08-05T10:00:00Z",
    type: "call",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-2", name: "Mainframe Modernization", closeDate: "2024-03-31", stage: "Prospect", revenue: 500000, stageAdjustedRevenue: 50000 }],
  },
  {
    id: "myp-mm-2",
    timestamp: "2023-09-12T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Stakeholder alignment workshop",
    linkedOpportunities: [{ id: "myp-opp-2", name: "Mainframe Modernization", closeDate: "2024-03-31", stage: "Prospect", revenue: 500000, stageAdjustedRevenue: 50000 }],
  },
  {
    id: "myp-mm-3",
    timestamp: "2023-10-20T09:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Legacy assessment demo",
    linkedOpportunities: [{ id: "myp-opp-2", name: "Mainframe Modernization", closeDate: "2024-03-31", stage: "Qualified", revenue: 500000, stageAdjustedRevenue: 100000 }],
  },
  {
    id: "myp-mm-4",
    timestamp: "2023-11-15T11:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Technical deep dive",
    linkedOpportunities: [{ id: "myp-opp-2", name: "Mainframe Modernization", closeDate: "2024-03-31", stage: "Technical Validation", revenue: 500000, stageAdjustedRevenue: 200000 }],
  },
  {
    id: "myp-mm-5",
    timestamp: "2023-12-10T15:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Budget review",
    linkedOpportunities: [{ id: "myp-opp-2", name: "Mainframe Modernization", closeDate: "2024-03-31", stage: "Business Validation", revenue: 500000, stageAdjustedRevenue: 300000 }],
  },
  {
    id: "myp-mm-6",
    timestamp: "2024-01-22T10:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Revised proposal submission",
    linkedOpportunities: [{ id: "myp-opp-2", name: "Mainframe Modernization", closeDate: "2024-03-31", stage: "Business Validation", revenue: 500000, stageAdjustedRevenue: 300000 }],
  },
  {
    id: "myp-mm-7",
    timestamp: "2024-03-01T09:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Deal lost — competitor selected",
    linkedOpportunities: [{ id: "myp-opp-2", name: "Mainframe Modernization", closeDate: "2024-03-31", stage: "Closed Lost", revenue: 500000, stageAdjustedRevenue: 0 }],
  },
  // --- Opp 3: Container Platform (2024-06-30, Committed, 280k) — 7 activities ---
  {
    id: "myp-cp-1",
    timestamp: "2023-12-05T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-3", name: "Container Platform", closeDate: "2024-06-30", stage: "Prospect", revenue: 280000, stageAdjustedRevenue: 28000 }],
  },
  {
    id: "myp-cp-2",
    timestamp: "2024-01-15T14:00:00Z",
    type: "call",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Requirements gathering",
    linkedOpportunities: [{ id: "myp-opp-3", name: "Container Platform", closeDate: "2024-06-30", stage: "Qualified", revenue: 280000, stageAdjustedRevenue: 56000 }],
  },
  {
    id: "myp-cp-3",
    timestamp: "2024-02-10T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Platform demo and PoC walkthrough",
    linkedOpportunities: [{ id: "myp-opp-3", name: "Container Platform", closeDate: "2024-06-30", stage: "Technical Validation", revenue: 280000, stageAdjustedRevenue: 112000 }],
  },
  {
    id: "myp-cp-4",
    timestamp: "2024-03-08T11:00:00Z",
    type: "workshop",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Security assessment",
    linkedOpportunities: [{ id: "myp-opp-3", name: "Container Platform", closeDate: "2024-06-30", stage: "Technical Validation", revenue: 280000, stageAdjustedRevenue: 112000 }],
  },
  {
    id: "myp-cp-5",
    timestamp: "2024-04-02T15:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Executive briefing",
    linkedOpportunities: [{ id: "myp-opp-3", name: "Container Platform", closeDate: "2024-06-30", stage: "Business Validation", revenue: 280000, stageAdjustedRevenue: 168000 }],
  },
  {
    id: "myp-cp-6",
    timestamp: "2024-05-10T09:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Contract negotiation",
    linkedOpportunities: [{ id: "myp-opp-3", name: "Container Platform", closeDate: "2024-06-30", stage: "Committed", revenue: 280000, stageAdjustedRevenue: 224000 }],
  },
  {
    id: "myp-cp-7",
    timestamp: "2024-06-01T10:00:00Z",
    type: "call",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Implementation kickoff planning",
    linkedOpportunities: [{ id: "myp-opp-3", name: "Container Platform", closeDate: "2024-06-30", stage: "Committed", revenue: 280000, stageAdjustedRevenue: 224000 }],
  },
  // --- Opp 4: Runtime Upgrade (2024-09-15, Launched, 150k) — 6 activities ---
  {
    id: "myp-ru-1",
    timestamp: "2024-03-01T09:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-4", name: "Runtime Upgrade", closeDate: "2024-09-15", stage: "Prospect", revenue: 150000, stageAdjustedRevenue: 15000 }],
  },
  {
    id: "myp-ru-2",
    timestamp: "2024-04-10T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Compatibility assessment",
    linkedOpportunities: [{ id: "myp-opp-4", name: "Runtime Upgrade", closeDate: "2024-09-15", stage: "Qualified", revenue: 150000, stageAdjustedRevenue: 30000 }],
  },
  {
    id: "myp-ru-3",
    timestamp: "2024-05-15T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }, { name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Migration path demo",
    linkedOpportunities: [{ id: "myp-opp-4", name: "Runtime Upgrade", closeDate: "2024-09-15", stage: "Technical Validation", revenue: 150000, stageAdjustedRevenue: 60000 }],
  },
  {
    id: "myp-ru-4",
    timestamp: "2024-06-20T11:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Pricing proposal",
    linkedOpportunities: [{ id: "myp-opp-4", name: "Runtime Upgrade", closeDate: "2024-09-15", stage: "Business Validation", revenue: 150000, stageAdjustedRevenue: 90000 }],
  },
  {
    id: "myp-ru-5",
    timestamp: "2024-07-25T15:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Executive briefing",
    linkedOpportunities: [{ id: "myp-opp-4", name: "Runtime Upgrade", closeDate: "2024-09-15", stage: "Committed", revenue: 150000, stageAdjustedRevenue: 120000 }],
  },
  {
    id: "myp-ru-6",
    timestamp: "2024-09-01T09:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Go-live planning",
    linkedOpportunities: [{ id: "myp-opp-4", name: "Runtime Upgrade", closeDate: "2024-09-15", stage: "Launched", revenue: 150000, stageAdjustedRevenue: 150000 }],
  },
  // --- Opp 5: Data Lake Build (2024-12-20, Completed, 420k) — 8 activities ---
  {
    id: "myp-dl-1",
    timestamp: "2024-03-20T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Prospect", revenue: 420000, stageAdjustedRevenue: 42000 }],
  },
  {
    id: "myp-dl-2",
    timestamp: "2024-04-25T14:00:00Z",
    type: "call",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }, { name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Data strategy alignment",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Prospect", revenue: 420000, stageAdjustedRevenue: 42000 }],
  },
  {
    id: "myp-dl-3",
    timestamp: "2024-05-30T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Architecture review",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Qualified", revenue: 420000, stageAdjustedRevenue: 84000 }],
  },
  {
    id: "myp-dl-4",
    timestamp: "2024-07-05T11:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Technical deep dive",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Technical Validation", revenue: 420000, stageAdjustedRevenue: 168000 }],
  },
  {
    id: "myp-dl-5",
    timestamp: "2024-08-10T15:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Security assessment",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Technical Validation", revenue: 420000, stageAdjustedRevenue: 168000 }],
  },
  {
    id: "myp-dl-6",
    timestamp: "2024-09-15T09:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Contract negotiation",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Business Validation", revenue: 420000, stageAdjustedRevenue: 252000 }],
  },
  {
    id: "myp-dl-7",
    timestamp: "2024-10-20T10:00:00Z",
    type: "call",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Go-live planning",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Committed", revenue: 420000, stageAdjustedRevenue: 336000 }],
  },
  {
    id: "myp-dl-8",
    timestamp: "2024-12-01T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }, { name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Project completion review",
    linkedOpportunities: [{ id: "myp-opp-5", name: "Data Lake Build", closeDate: "2024-12-20", stage: "Completed", revenue: 420000, stageAdjustedRevenue: 420000 }],
  },
  // --- Opp 6: API Gateway Rollout (2025-03-31, Qualified, 180k) — 5 activities ---
  {
    id: "myp-ag-1",
    timestamp: "2024-10-01T09:00:00Z",
    type: "call",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-6", name: "API Gateway Rollout", closeDate: "2025-03-31", stage: "Prospect", revenue: 180000, stageAdjustedRevenue: 18000 }],
  },
  {
    id: "myp-ag-2",
    timestamp: "2024-11-08T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }, { name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "API landscape assessment",
    linkedOpportunities: [{ id: "myp-opp-6", name: "API Gateway Rollout", closeDate: "2025-03-31", stage: "Prospect", revenue: 180000, stageAdjustedRevenue: 18000 }],
  },
  {
    id: "myp-ag-3",
    timestamp: "2024-12-12T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Gateway platform demo",
    linkedOpportunities: [{ id: "myp-opp-6", name: "API Gateway Rollout", closeDate: "2025-03-31", stage: "Qualified", revenue: 180000, stageAdjustedRevenue: 36000 }],
  },
  {
    id: "myp-ag-4",
    timestamp: "2025-01-15T11:00:00Z",
    type: "email",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Integration requirements document",
    linkedOpportunities: [{ id: "myp-opp-6", name: "API Gateway Rollout", closeDate: "2025-03-31", stage: "Qualified", revenue: 180000, stageAdjustedRevenue: 36000 }],
  },
  {
    id: "myp-ag-5",
    timestamp: "2025-02-20T15:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Budget alignment call",
    linkedOpportunities: [{ id: "myp-opp-6", name: "API Gateway Rollout", closeDate: "2025-03-31", stage: "Qualified", revenue: 180000, stageAdjustedRevenue: 36000 }],
  },
  // --- Opp 7: Kubernetes Adoption (2025-06-30, Technical Validation, 60k) — 5 activities ---
  {
    id: "myp-ka-1",
    timestamp: "2025-01-10T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-7", name: "Kubernetes Adoption", closeDate: "2025-06-30", stage: "Prospect", revenue: 60000, stageAdjustedRevenue: 6000 }],
  },
  {
    id: "myp-ka-2",
    timestamp: "2025-02-05T14:00:00Z",
    type: "call",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Container orchestration needs analysis",
    linkedOpportunities: [{ id: "myp-opp-7", name: "Kubernetes Adoption", closeDate: "2025-06-30", stage: "Qualified", revenue: 60000, stageAdjustedRevenue: 12000 }],
  },
  {
    id: "myp-ka-3",
    timestamp: "2025-03-10T10:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Eve White", role: "IT Manager", country: "AU" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Hands-on K8s workshop",
    linkedOpportunities: [{ id: "myp-opp-7", name: "Kubernetes Adoption", closeDate: "2025-06-30", stage: "Technical Validation", revenue: 60000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "myp-ka-4",
    timestamp: "2025-04-15T11:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Cluster management demo",
    linkedOpportunities: [{ id: "myp-opp-7", name: "Kubernetes Adoption", closeDate: "2025-06-30", stage: "Technical Validation", revenue: 60000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "myp-ka-5",
    timestamp: "2025-05-20T15:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "PoC results summary",
    linkedOpportunities: [{ id: "myp-opp-7", name: "Kubernetes Adoption", closeDate: "2025-06-30", stage: "Technical Validation", revenue: 60000, stageAdjustedRevenue: 24000 }],
  },
  // --- Opp 8: Observability Platform (2025-10-31, Prospect, 240k) — 6 activities ---
  {
    id: "myp-ob-1",
    timestamp: "2025-04-01T09:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Initial discovery call",
    linkedOpportunities: [{ id: "myp-opp-8", name: "Observability Platform", closeDate: "2025-10-31", stage: "Prospect", revenue: 240000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "myp-ob-2",
    timestamp: "2025-05-05T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Monitoring landscape review",
    linkedOpportunities: [{ id: "myp-opp-8", name: "Observability Platform", closeDate: "2025-10-31", stage: "Prospect", revenue: 240000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "myp-ob-3",
    timestamp: "2025-06-10T10:00:00Z",
    type: "email",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Tooling comparison document",
    linkedOpportunities: [{ id: "myp-opp-8", name: "Observability Platform", closeDate: "2025-10-31", stage: "Prospect", revenue: 240000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "myp-ob-4",
    timestamp: "2025-07-15T11:00:00Z",
    type: "demo",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Platform capabilities demo",
    linkedOpportunities: [{ id: "myp-opp-8", name: "Observability Platform", closeDate: "2025-10-31", stage: "Prospect", revenue: 240000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "myp-ob-5",
    timestamp: "2025-08-20T15:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Hands-on evaluation workshop",
    linkedOpportunities: [{ id: "myp-opp-8", name: "Observability Platform", closeDate: "2025-10-31", stage: "Prospect", revenue: 240000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "myp-ob-6",
    timestamp: "2025-09-25T09:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Stakeholder check-in",
    linkedOpportunities: [{ id: "myp-opp-8", name: "Observability Platform", closeDate: "2025-10-31", stage: "Prospect", revenue: 240000, stageAdjustedRevenue: 24000 }],
  },
];

// Hand-crafted 6 opportunities closing in 2026, ~40 activities with varied types and stages
export const sixOpps2026: Activity[] = [
  // --- Opp 1: APAC Cloud Migration (2026-02-15, Prospect, 120k) — 4 activities ---
  {
    id: "six-acm-1",
    timestamp: "2025-09-10T09:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Initial outreach call",
    linkedOpportunities: [{ id: "opp-2026-01", name: "APAC Cloud Migration", closeDate: "2026-02-15", stage: "Prospect", revenue: 120000, stageAdjustedRevenue: 12000 }],
  },
  {
    id: "six-acm-2",
    timestamp: "2025-10-22T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Cloud readiness assessment",
    linkedOpportunities: [{ id: "opp-2026-01", name: "APAC Cloud Migration", closeDate: "2026-02-15", stage: "Prospect", revenue: 120000, stageAdjustedRevenue: 18000 }],
  },
  {
    id: "six-acm-3",
    timestamp: "2025-12-05T10:00:00Z",
    type: "email",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Migration strategy document",
    linkedOpportunities: [{ id: "opp-2026-01", name: "APAC Cloud Migration", closeDate: "2026-02-15", stage: "Prospect", revenue: 120000, stageAdjustedRevenue: 24000 }],
  },
  {
    id: "six-acm-4",
    timestamp: "2026-01-15T11:00:00Z",
    type: "demo",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Migration tooling demo",
    linkedOpportunities: [{ id: "opp-2026-01", name: "APAC Cloud Migration", closeDate: "2026-02-15", stage: "Prospect", revenue: 120000, stageAdjustedRevenue: 30000 }],
  },
  // --- Opp 2: EMEA Data Platform (2026-04-20, Qualified, 250k) — 6 activities ---
  {
    id: "six-edp-1",
    timestamp: "2025-11-01T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Data platform discovery",
    linkedOpportunities: [{ id: "opp-2026-02", name: "EMEA Data Platform", closeDate: "2026-04-20", stage: "Prospect", revenue: 250000, stageAdjustedRevenue: 25000 }],
  },
  {
    id: "six-edp-2",
    timestamp: "2025-12-10T14:00:00Z",
    type: "call",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Requirements deep dive",
    linkedOpportunities: [{ id: "opp-2026-02", name: "EMEA Data Platform", closeDate: "2026-04-20", stage: "Prospect", revenue: 250000, stageAdjustedRevenue: 37500 }],
  },
  {
    id: "six-edp-3",
    timestamp: "2026-01-08T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Platform capabilities demo",
    linkedOpportunities: [{ id: "opp-2026-02", name: "EMEA Data Platform", closeDate: "2026-04-20", stage: "Qualified", revenue: 250000, stageAdjustedRevenue: 50000 }],
  },
  {
    id: "six-edp-4",
    timestamp: "2026-02-05T11:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Hands-on data pipeline workshop",
    linkedOpportunities: [{ id: "opp-2026-02", name: "EMEA Data Platform", closeDate: "2026-04-20", stage: "Qualified", revenue: 250000, stageAdjustedRevenue: 62500 }],
  },
  {
    id: "six-edp-5",
    timestamp: "2026-03-02T15:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Pricing proposal",
    linkedOpportunities: [{ id: "opp-2026-02", name: "EMEA Data Platform", closeDate: "2026-04-20", stage: "Qualified", revenue: 250000, stageAdjustedRevenue: 75000 }],
  },
  {
    id: "six-edp-6",
    timestamp: "2026-04-01T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }, { name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Budget alignment meeting",
    linkedOpportunities: [{ id: "opp-2026-02", name: "EMEA Data Platform", closeDate: "2026-04-20", stage: "Qualified", revenue: 250000, stageAdjustedRevenue: 87500 }],
  },
  // --- Opp 3: NA Security Upgrade (2026-06-10, Technical Validation, 75k) — 8 activities ---
  {
    id: "six-nsu-1",
    timestamp: "2025-12-15T09:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Security posture review call",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Prospect", revenue: 75000, stageAdjustedRevenue: 7500 }],
  },
  {
    id: "six-nsu-2",
    timestamp: "2026-01-10T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }, { name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Threat landscape assessment",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Prospect", revenue: 75000, stageAdjustedRevenue: 11250 }],
  },
  {
    id: "six-nsu-3",
    timestamp: "2026-02-01T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Security tooling demo",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Qualified", revenue: 75000, stageAdjustedRevenue: 15000 }],
  },
  {
    id: "six-nsu-4",
    timestamp: "2026-02-20T11:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Penetration test review workshop",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Qualified", revenue: 75000, stageAdjustedRevenue: 18750 }],
  },
  {
    id: "six-nsu-5",
    timestamp: "2026-03-10T15:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Compliance requirements document",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Technical Validation", revenue: 75000, stageAdjustedRevenue: 22500 }],
  },
  {
    id: "six-nsu-6",
    timestamp: "2026-04-05T09:00:00Z",
    type: "call",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Architecture validation call",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Technical Validation", revenue: 75000, stageAdjustedRevenue: 26250 }],
  },
  {
    id: "six-nsu-7",
    timestamp: "2026-05-01T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Procurement review",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Technical Validation", revenue: 75000, stageAdjustedRevenue: 30000 }],
  },
  {
    id: "six-nsu-8",
    timestamp: "2026-05-25T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Final technical validation demo",
    linkedOpportunities: [{ id: "opp-2026-03", name: "NA Security Upgrade", closeDate: "2026-06-10", stage: "Technical Validation", revenue: 75000, stageAdjustedRevenue: 33750 }],
  },
  // --- Opp 4: Global ERP Rollout (2026-08-30, Business Validation, 400k) — 10 activities ---
  {
    id: "six-ger-1",
    timestamp: "2026-01-05T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "ERP modernization discovery",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Prospect", revenue: 400000, stageAdjustedRevenue: 40000 }],
  },
  {
    id: "six-ger-2",
    timestamp: "2026-01-28T14:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Stakeholder alignment call",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Prospect", revenue: 400000, stageAdjustedRevenue: 60000 }],
  },
  {
    id: "six-ger-3",
    timestamp: "2026-02-18T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "ERP platform demo",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Qualified", revenue: 400000, stageAdjustedRevenue: 80000 }],
  },
  {
    id: "six-ger-4",
    timestamp: "2026-03-12T11:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Integration architecture workshop",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Qualified", revenue: 400000, stageAdjustedRevenue: 100000 }],
  },
  {
    id: "six-ger-5",
    timestamp: "2026-04-08T15:00:00Z",
    type: "email",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Technical requirements document",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Technical Validation", revenue: 400000, stageAdjustedRevenue: 120000 }],
  },
  {
    id: "six-ger-6",
    timestamp: "2026-05-01T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }, { name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "PoC results review",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Technical Validation", revenue: 400000, stageAdjustedRevenue: 140000 }],
  },
  {
    id: "six-ger-7",
    timestamp: "2026-05-22T14:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Budget and timeline discussion",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Business Validation", revenue: 400000, stageAdjustedRevenue: 160000 }],
  },
  {
    id: "six-ger-8",
    timestamp: "2026-06-15T10:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }, { name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Executive steering committee demo",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Business Validation", revenue: 400000, stageAdjustedRevenue: 180000 }],
  },
  {
    id: "six-ger-9",
    timestamp: "2026-07-10T11:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Contract terms proposal",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Business Validation", revenue: 400000, stageAdjustedRevenue: 200000 }],
  },
  {
    id: "six-ger-10",
    timestamp: "2026-08-05T15:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Final business case presentation",
    linkedOpportunities: [{ id: "opp-2026-04", name: "Global ERP Rollout", closeDate: "2026-08-30", stage: "Business Validation", revenue: 400000, stageAdjustedRevenue: 220000 }],
  },
  // --- Opp 5: LATAM Analytics (2026-10-15, Launched, 180k) — 5 activities ---
  {
    id: "six-la-1",
    timestamp: "2026-05-10T09:00:00Z",
    type: "call",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Analytics platform discovery",
    linkedOpportunities: [{ id: "opp-2026-05", name: "LATAM Analytics", closeDate: "2026-10-15", stage: "Prospect", revenue: 180000, stageAdjustedRevenue: 18000 }],
  },
  {
    id: "six-la-2",
    timestamp: "2026-06-05T14:00:00Z",
    type: "meeting",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }],
    description: "Data strategy alignment",
    linkedOpportunities: [{ id: "opp-2026-05", name: "LATAM Analytics", closeDate: "2026-10-15", stage: "Qualified", revenue: 180000, stageAdjustedRevenue: 36000 }],
  },
  {
    id: "six-la-3",
    timestamp: "2026-07-08T10:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Analytics hands-on workshop",
    linkedOpportunities: [{ id: "opp-2026-05", name: "LATAM Analytics", closeDate: "2026-10-15", stage: "Technical Validation", revenue: 180000, stageAdjustedRevenue: 54000 }],
  },
  {
    id: "six-la-4",
    timestamp: "2026-08-15T11:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }],
    description: "Contract and pricing proposal",
    linkedOpportunities: [{ id: "opp-2026-05", name: "LATAM Analytics", closeDate: "2026-10-15", stage: "Business Validation", revenue: 180000, stageAdjustedRevenue: 90000 }],
  },
  {
    id: "six-la-5",
    timestamp: "2026-09-20T15:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    partners: [{ name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Go-live readiness demo",
    linkedOpportunities: [{ id: "opp-2026-05", name: "LATAM Analytics", closeDate: "2026-10-15", stage: "Launched", revenue: 180000, stageAdjustedRevenue: 144000 }],
  },
  // --- Opp 6: MEA Digital Transform (2026-12-01, Prospect, 310k) — 7 activities ---
  {
    id: "six-mdt-1",
    timestamp: "2026-06-10T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Digital transformation discovery",
    linkedOpportunities: [{ id: "opp-2026-06", name: "MEA Digital Transform", closeDate: "2026-12-01", stage: "Prospect", revenue: 310000, stageAdjustedRevenue: 31000 }],
  },
  {
    id: "six-mdt-2",
    timestamp: "2026-07-02T14:00:00Z",
    type: "call",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }, { name: "Eve White", role: "IT Manager", country: "AU" }],
    partners: [{ name: "Pat Taylor", role: "Implementation Consultant", country: "IE" }, { name: "Quinn Adams", role: "Integration Specialist", country: "NZ" }],
    description: "Stakeholder mapping call",
    linkedOpportunities: [{ id: "opp-2026-06", name: "MEA Digital Transform", closeDate: "2026-12-01", stage: "Prospect", revenue: 310000, stageAdjustedRevenue: 46500 }],
  },
  {
    id: "six-mdt-3",
    timestamp: "2026-07-25T10:00:00Z",
    type: "email",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Current state assessment document",
    linkedOpportunities: [{ id: "opp-2026-06", name: "MEA Digital Transform", closeDate: "2026-12-01", stage: "Prospect", revenue: 310000, stageAdjustedRevenue: 62000 }],
  },
  {
    id: "six-mdt-4",
    timestamp: "2026-08-18T11:00:00Z",
    type: "demo",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Platform capabilities overview",
    linkedOpportunities: [{ id: "opp-2026-06", name: "MEA Digital Transform", closeDate: "2026-12-01", stage: "Prospect", revenue: 310000, stageAdjustedRevenue: 77500 }],
  },
  {
    id: "six-mdt-5",
    timestamp: "2026-09-10T15:00:00Z",
    type: "workshop",
    sellers: [{ name: "Carol Davis", role: "Solutions Architect", country: "DE" }, { name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Transformation roadmap workshop",
    linkedOpportunities: [{ id: "opp-2026-06", name: "MEA Digital Transform", closeDate: "2026-12-01", stage: "Prospect", revenue: 310000, stageAdjustedRevenue: 93000 }],
  },
  {
    id: "six-mdt-6",
    timestamp: "2026-10-05T09:00:00Z",
    type: "meeting",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Frank Castle", role: "Procurement Lead", country: "IN" }, { name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Executive briefing",
    linkedOpportunities: [{ id: "opp-2026-06", name: "MEA Digital Transform", closeDate: "2026-12-01", stage: "Prospect", revenue: 310000, stageAdjustedRevenue: 108500 }],
  },
  {
    id: "six-mdt-7",
    timestamp: "2026-11-01T14:00:00Z",
    type: "call",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }, { name: "Carol Davis", role: "Solutions Architect", country: "DE" }],
    customers: [{ name: "Eve White", role: "IT Manager", country: "AU" }],
    description: "Follow-up and next steps",
    linkedOpportunities: [{ id: "opp-2026-06", name: "MEA Digital Transform", closeDate: "2026-12-01", stage: "Prospect", revenue: 310000, stageAdjustedRevenue: 124000 }],
  },
];

// Hand-crafted mixed bound and free activities dataset
export const mixedBoundAndFree: Activity[] = [
  {
    id: "ms-both-activity-1",
    timestamp: "2023-01-15T10:00:00Z",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Q1 Prospect Call",
    linkedOpportunities: [
      {
        id: "opp-ms-both-1",
        closeDate: "2023-06-30",
        stage: "Prospect",
        revenue: 50000,
        stageAdjustedRevenue: 5000,
      },
    ],
  },
  {
    id: "ms-both-activity-2",
    timestamp: "2023-02-20T14:00:00Z",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Q2 Demo",
    linkedOpportunities: [
      {
        id: "opp-ms-both-1",
        closeDate: "2023-06-30",
        stage: "Technical Validation",
        revenue: 50000,
        stageAdjustedRevenue: 25000,
      },
    ],
  },
  {
    id: "ms-both-activity-3",
    timestamp: "2023-03-10T09:00:00Z",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Eve Green", role: "CFO", country: "CH" }],
    description: "Q3 Technical Review",
    linkedOpportunities: [
      {
        id: "opp-ms-both-2",
        closeDate: "2023-07-31",
        stage: "Qualified",
        revenue: 75000,
        stageAdjustedRevenue: 37500,
      },
    ],
  },
  {
    id: "ms-both-activity-4",
    timestamp: "2023-04-15T11:00:00Z",
    sellers: [{ name: "Carol White", role: "Account Executive", country: "IT" }],
    customers: [{ name: "Frank Black", role: "CTO", country: "NO" }],
    description: "Q4 Follow-up",
    linkedOpportunities: [
      {
        id: "opp-ms-both-3",
        closeDate: "2023-08-31",
        stage: "Business Validation",
        revenue: 120000,
        stageAdjustedRevenue: 96000,
      },
    ],
  },
  {
    id: "mixed-free-1",
    timestamp: "2023-01-20T10:00:00Z",
    sellers: [{ name: "Alice Smith", role: "Account Executive", country: "US" }],
    customers: [{ name: "Charlie Brown", role: "CTO", country: "JP" }],
    description: "Unlinked Activity 1",
    linkedOpportunities: [],
  },
  {
    id: "mixed-free-2",
    timestamp: "2023-03-05T14:00:00Z",
    sellers: [{ name: "Bob Jones", role: "Sales Engineer", country: "GB" }],
    customers: [{ name: "Diana Prince", role: "VP Engineering", country: "BR" }],
    description: "Unlinked Activity 2",
    linkedOpportunities: [],
  },
];

export const datasets = {
  "Example (Live)": exampleActivities,
  "6 Opps / 2026 (40 Activities)": sixOpps2026,
  "Multi-Year Portfolio (8 Opps)": multiYearPortfolio,
  "Mixed: Bound and Free Activities": mixedBoundAndFree,
  "Edge: Empty": edgeCaseEmpty,
};